%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Just plot the data generated by the script
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Metadata
% Written by    : Nathanaël Esnault
% Verified by   : N/A
% Creation date : 2020-12-01
% Version       : 0.1 (finished on ...)
% Modifications :
% Known bugs    :

%% Functions associated with this code :

%% Possible Improvements


%%
if Do.SaveFigures
    CreateSavedDataFolders; % call another script
end

%reformat time
globalTime_plot         = seconds(globalTime);
switch displayTimeFormat
    case 'h+m'
        globalTime_plot.Format  = 'hh:mm';
        plotAxisLabelTime       = 'Time [hours:minutes]';
    case 'm+fs'
        globalTime_plot.Format  = 'mm:ss.SSS';
        plotAxisLabelTime       = 'Time [minutes:seconds]';
    case 's'
        globalTime_plot.Format  = 's';
        plotAxisLabelTime       = 'Time [s]';
    otherwise
        disp('Problem formating time');
end

%--------------------------------------------------------------------------
% Check Time
figure()
plot(globalTime_plot)
title('Time check')
ylabel(plotAxisLabelTime)
xlabel('Epoch [N/A]')
grid on
% xlim([-10 60])
% ylim([-10 60])
% axis square
% print(gcf,'-dpng', 'Time','-r1200');
% print(gcf,'-djpeg', 'Time','-r1200');

%--------------------------------------------------------------------------
% check calibrated + filtered values (3 subplots)
figure()
subplot(2,1,1)
plot(globalTime_plot,accelReadings)
title('Accelerometer Reading')
ylabel('Acceleration [m/s^2]')
xlabel(plotAxisLabelTime)
l = legend(...
    'X',...
    'Y',...
    'Z'...
    );
grid on


% subplot(3,1,2)
% plot(globalTime_plot,magReadings)
% title('Magnetometer Reading')
% ylabel('Magnetic Field (\muT)')
% xlabel(plotAxisLabelTime)
% l = legend(...
%     'X',...
%     'Y',...
%     'Z'...
%     );
% grid on

subplot(2,1,2)
plot(globalTime_plot,gyroReadings)
title('Gyroscope Reading')
ylabel('Angular Velocity (rad/s)')
xlabel(plotAxisLabelTime)
l = legend(...
    'X',...
    'Y',...
    'Z'...
    );
grid on
% xlim([-10 60])
% ylim([-10 60])
% axis square
% print(gcf,'-dpng', 'Processed data','-r1200');
% print(gcf,'-djpeg', 'Processed data','-r1200');

%--------------------------------------------------------------------------
% Check Euler angles (not filtered but issued from filted data)
figure()
plot(globalTime_plot,orientationEulerAngles(:,3), ...
    globalTime_plot,orientationEulerAngles(:,2), ...
    globalTime_plot,orientationEulerAngles(:,1))
xlabel(plotAxisLabelTime)
ylabel('Angle [°]')
title('Orientation over Time')
l = legend(...
    'Roll',...
    'Pitch',...
    'Yaw'...
    );
grid on
% xlim([-10 60])
% ylim([-10 60])
% axis square
% print(gcf,'-dpng', 'Euler','-r1200');
% print(gcf,'-djpeg', 'Euler','-r1200');

%--------------------------------------------------------------------------
% Check Euler angles unwrapped (not filtered but issued from filted data)
figure()
plot(globalTime_plot,unwrap(orientationEulerAngles(:,3)), ...
    globalTime_plot,unwrap(orientationEulerAngles(:,2)), ...
    globalTime_plot,unwrap(orientationEulerAngles(:,1)))
xlabel(plotAxisLabelTime)
ylabel('Angle [°]')
title('Orientation over Time (unwrapped)')
l = legend(...
    'Roll',...
    'Pitch',...
    'Yaw'...
    );
grid on